// Auto-generated by scripts/update-icons-index.js
// DO NOT EDIT MANUALLY

import AcceptIcon from './components/AcceptIcon';
import AddIcon from './components/AddIcon';
import AlarmClockIcon from './components/AlarmClockIcon';
import AlignCenterIcon from './components/AlignCenterIcon';
import AlignJustifyIcon from './components/AlignJustifyIcon';
import AlignLeftIcon from './components/AlignLeftIcon';
import AlignRightIcon from './components/AlignRightIcon';
import BackIcon from './components/BackIcon';
import BlockedIcon from './components/BlockedIcon';
import BoldIcon from './components/BoldIcon';
import CalendarIcon from './components/CalendarIcon';
import CancelIcon from './components/CancelIcon';
import CheckMarkIcon from './components/CheckMarkIcon';
import ChevronDownIcon from './components/ChevronDownIcon';
import ChevronDownMedIcon from './components/ChevronDownMedIcon';
import ChevronDownSmallIcon from './components/ChevronDownSmallIcon';
import ChevronLeftIcon from './components/ChevronLeftIcon';
import ChevronLeftMedIcon from './components/ChevronLeftMedIcon';
import ChevronLeftSmallIcon from './components/ChevronLeftSmallIcon';
import ChevronRightIcon from './components/ChevronRightIcon';
import ChevronRightMedIcon from './components/ChevronRightMedIcon';
import ChevronRightSmallIcon from './components/ChevronRightSmallIcon';
import ChevronUpIcon from './components/ChevronUpIcon';
import ChevronUpMedIcon from './components/ChevronUpMedIcon';
import ChevronUpSmallIcon from './components/ChevronUpSmallIcon';
import CirclePauseIcon from './components/CirclePauseIcon';
import CircleStopIcon from './components/CircleStopIcon';
import ClearIcon from './components/ClearIcon';
import ClockIcon from './components/ClockIcon';
import CompletedIcon from './components/CompletedIcon';
import ContactIcon from './components/ContactIcon';
import CopyIcon from './components/CopyIcon';
import CubeTreeFilledIcon from './components/CubeTreeFilledIcon';
import CutIcon from './components/CutIcon';
import DatabaseFilledIcon from './components/DatabaseFilledIcon';
import DeleteIcon from './components/DeleteIcon';
import DocumentIcon from './components/DocumentIcon';
import DownIcon from './components/DownIcon';
import DownloadIcon from './components/DownloadIcon';
import EditIcon from './components/EditIcon';
import ErrorBadgeIcon from './components/ErrorBadgeIcon';
import ErrorIcon from './components/ErrorIcon';
import FastForwardIcon from './components/FastForwardIcon';
import FileCSSIcon from './components/FileCSSIcon';
import FileCodeIcon from './components/FileCodeIcon';
import FileHTMLIcon from './components/FileHTMLIcon';
import FileSymlinkIcon from './components/FileSymlinkIcon';
import FilterIcon from './components/FilterIcon';
import FlagIcon from './components/FlagIcon';
import FolderIcon from './components/FolderIcon';
import FolderOpenIcon from './components/FolderOpenIcon';
import FontColorIcon from './components/FontColorIcon';
import FontDecreaseIcon from './components/FontDecreaseIcon';
import FontIncreaseIcon from './components/FontIncreaseIcon';
import FontSizeIcon from './components/FontSizeIcon';
import ForwardIcon from './components/ForwardIcon';
import FullScreenIcon from './components/FullScreenIcon';
import GroupIcon from './components/GroupIcon';
import HeartIcon from './components/HeartIcon';
import HideIcon from './components/HideIcon';
import HomeIcon from './components/HomeIcon';
import InfoIcon from './components/InfoIcon';
import ItalicIcon from './components/ItalicIcon';
import LineSpacingIcon from './components/LineSpacingIcon';
import LinkIcon from './components/LinkIcon';
import LocationIcon from './components/LocationIcon';
import LockIcon from './components/LockIcon';
import MailIcon from './components/MailIcon';
import NextIcon from './components/NextIcon';
import PageIcon from './components/PageIcon';
import PartyLeaderIcon from './components/PartyLeaderIcon';
import PasteIcon from './components/PasteIcon';
import PauseIcon from './components/PauseIcon';
import PeopleIcon from './components/PeopleIcon';
import PermissionsIcon from './components/PermissionsIcon';
import PinIcon from './components/PinIcon';
import PlayIcon from './components/PlayIcon';
import PlugDisconnectedFilledIcon from './components/PlugDisconnectedFilledIcon';
import PlugDisconnectedIcon from './components/PlugDisconnectedIcon';
import PreviousIcon from './components/PreviousIcon';
import PrintIcon from './components/PrintIcon';
import ProtectedDocumentIcon from './components/ProtectedDocumentIcon';
import RedoIcon from './components/RedoIcon';
import RefreshIcon from './components/RefreshIcon';
import RewindIcon from './components/RewindIcon';
import SaveIcon from './components/SaveIcon';
import SearchIcon from './components/SearchIcon';
import SettingsIcon from './components/SettingsIcon';
import ShareIcon from './components/ShareIcon';
import SortIcon from './components/SortIcon';
import SpinnerFilledIcon from './components/SpinnerFilledIcon';
import StatusTriangleIcon from './components/StatusTriangleIcon';
import StopIcon from './components/StopIcon';
import StrikethroughIcon from './components/StrikethroughIcon';
import TableEditFilledIcon from './components/TableEditFilledIcon';
import TableFilledIcon from './components/TableFilledIcon';
import TagIcon from './components/TagIcon';
import TimerIcon from './components/TimerIcon';
import UnderlineIcon from './components/UnderlineIcon';
import UndoIcon from './components/UndoIcon';
import UnknownIcon from './components/UnknownIcon';
import UnlockIcon from './components/UnlockIcon';
import UpIcon from './components/UpIcon';
import UploadIcon from './components/UploadIcon';
import VideoIcon from './components/VideoIcon';
import ViewIcon from './components/ViewIcon';
import WarningIcon from './components/WarningIcon';
import ZoomInIcon from './components/ZoomInIcon';
import ZoomOutIcon from './components/ZoomOutIcon';
import ZoomToFitIcon from './components/ZoomToFitIcon';

// 导出图标组件映射，供 Icon 组件使用
export const ICONS = {
  'accept': AcceptIcon,
  'add': AddIcon,
  'alarm-clock': AlarmClockIcon,
  'align-center': AlignCenterIcon,
  'align-justify': AlignJustifyIcon,
  'align-left': AlignLeftIcon,
  'align-right': AlignRightIcon,
  'back': BackIcon,
  'blocked': BlockedIcon,
  'bold': BoldIcon,
  'calendar': CalendarIcon,
  'cancel': CancelIcon,
  'check-mark': CheckMarkIcon,
  'chevron-down': ChevronDownIcon,
  'chevron-down-med': ChevronDownMedIcon,
  'chevron-down-small': ChevronDownSmallIcon,
  'chevron-left': ChevronLeftIcon,
  'chevron-left-med': ChevronLeftMedIcon,
  'chevron-left-small': ChevronLeftSmallIcon,
  'chevron-right': ChevronRightIcon,
  'chevron-right-med': ChevronRightMedIcon,
  'chevron-right-small': ChevronRightSmallIcon,
  'chevron-up': ChevronUpIcon,
  'chevron-up-med': ChevronUpMedIcon,
  'chevron-up-small': ChevronUpSmallIcon,
  'circle-pause': CirclePauseIcon,
  'circle-stop': CircleStopIcon,
  'clear': ClearIcon,
  'clock': ClockIcon,
  'completed': CompletedIcon,
  'contact': ContactIcon,
  'copy': CopyIcon,
  'cube-tree-filled': CubeTreeFilledIcon,
  'cut': CutIcon,
  'database-filled': DatabaseFilledIcon,
  'delete': DeleteIcon,
  'document': DocumentIcon,
  'down': DownIcon,
  'download': DownloadIcon,
  'edit': EditIcon,
  'error-badge': ErrorBadgeIcon,
  'error': ErrorIcon,
  'fast-forward': FastForwardIcon,
  'file-c-s-s': FileCSSIcon,
  'file-code': FileCodeIcon,
  'file-h-t-m-l': FileHTMLIcon,
  'file-symlink': FileSymlinkIcon,
  'filter': FilterIcon,
  'flag': FlagIcon,
  'folder': FolderIcon,
  'folder-open': FolderOpenIcon,
  'font-color': FontColorIcon,
  'font-decrease': FontDecreaseIcon,
  'font-increase': FontIncreaseIcon,
  'font-size': FontSizeIcon,
  'forward': ForwardIcon,
  'full-screen': FullScreenIcon,
  'group': GroupIcon,
  'heart': HeartIcon,
  'hide': HideIcon,
  'home': HomeIcon,
  'info': InfoIcon,
  'italic': ItalicIcon,
  'line-spacing': LineSpacingIcon,
  'link': LinkIcon,
  'location': LocationIcon,
  'lock': LockIcon,
  'mail': MailIcon,
  'next': NextIcon,
  'page': PageIcon,
  'party-leader': PartyLeaderIcon,
  'paste': PasteIcon,
  'pause': PauseIcon,
  'people': PeopleIcon,
  'permissions': PermissionsIcon,
  'pin': PinIcon,
  'play': PlayIcon,
  'plug-disconnected-filled': PlugDisconnectedFilledIcon,
  'plug-disconnected': PlugDisconnectedIcon,
  'previous': PreviousIcon,
  'print': PrintIcon,
  'protected-document': ProtectedDocumentIcon,
  'redo': RedoIcon,
  'refresh': RefreshIcon,
  'rewind': RewindIcon,
  'save': SaveIcon,
  'search': SearchIcon,
  'settings': SettingsIcon,
  'share': ShareIcon,
  'sort': SortIcon,
  'spinner-filled': SpinnerFilledIcon,
  'status-triangle': StatusTriangleIcon,
  'stop': StopIcon,
  'strikethrough': StrikethroughIcon,
  'table-edit-filled': TableEditFilledIcon,
  'table-filled': TableFilledIcon,
  'tag': TagIcon,
  'timer': TimerIcon,
  'underline': UnderlineIcon,
  'undo': UndoIcon,
  'unknown': UnknownIcon,
  'unlock': UnlockIcon,
  'up': UpIcon,
  'upload': UploadIcon,
  'video': VideoIcon,
  'view': ViewIcon,
  'warning': WarningIcon,
  'zoom-in': ZoomInIcon,
  'zoom-out': ZoomOutIcon,
  'zoom-to-fit': ZoomToFitIcon,
} as const;
