# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: today-ui npm publish 

on:
  push:
    branches: 
      - release

jobs:
  
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: release
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 7.3.0
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm -F=today-ui  install
      - name: build
        run: pnpm -F=today-ui build
      - name: publish
        run: cd ./packages/today-ui/ &&  npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 